### ISSUE TITLE
how to use Context-Aware Adapter

### ISSUE THREAD

**Issue by jupytera** [YangLing0818/ContextDiff#8]
Hello, I have reviewed the content you wrote in the ‘readme’ for text guided image generation. In the parameters of the second step 'Finetune Diffusion Model with Context-Aware Adapter', it seems that there is no option to call the pretrained Context-Aware Adapter in the first step. 
All the parameters are here:  CUDA_VISIBLE_DEVICES=0 finetune_diffusion.py --pretrained_model_name_or_path="stabilityai/stable-diffusion-2-1-base" --train_data_dir=./train2017 --use_ema --resolution=512 --center_crop --random_flip --train_batch_size=32 --gradient_accumulation_steps=1 --gradient_checkpointing --max_train_steps=50000 --checkpointing_steps=10000 --learning_rate=2e-05 --max_grad_norm=1 --lr_scheduler="constant" --lr_warmup_steps=0 
--output_dir="./output"
So I want to know how does the Context-Aware Adapter model work? Or which pretrained model mentioned in the parameters could be replaced by Context-Aware Adapter?Thank you for your help!

**Comment by ZhaochenYu0201** [comment]
Thank you for your  attention for our work. In the file finetune_diffusion.py, for the sake of convenient testing, we have directly employed a multitude of CLIP models to compose a simplified, readily deployable version of the Context-Aware Adapter, present in the code as MultiCLIP. Should you require the utilization of a Context-Aware Adapter trained by yourself, a few minor adjustments in the code are all that is necessary to substitute MultiCLIP with your own trained Context-Aware Adapter.

**Comment by jupytera** [comment]
Thank you for your answer! After completing the first step, I started running the finetune_diffusion.py. But I find whether I use three pretrained models in MultiCLIP or the model I trained, the following error message will appear:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/clip/clip.py", line 129, in load
    model = torch.jit.load(opened_file, map_location=device if jit else "cpu").eval()
  File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/torch/jit/_serialization.py", line 164, in load
    cpp_module = torch._C.import_ir_module_from_buffer(
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/autodl-tmp/ContextDiff-main/ContextDiff_image/finetune_diffusion.py", line 877, in <module>
    main()
  File "/root/autodl-tmp/ContextDiff-main/ContextDiff_image/finetune_diffusion.py", line 444, in main
    clip_model = MultiCLIP()
  File "/root/autodl-tmp/ContextDiff-main/ContextDiff_image/finetune_diffusion.py", line 51, in __init__
    model_myself,_ = clip.load("/root/autodl-tmp/ContextDiff-main/output/prior.pt", device=device)
  File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/clip/clip.py", line 136, in load
    state_dict = torch.load(opened_file, map_location="cpu")
  File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
I don't know if this has ever happened in your experiment.

**Comment by jupytera** [comment]
I still have one more confusion, the finetune_diffusion.py file seems to contain a complete training process. After the training is completed, how should we independently use the obtained model? Thank you again for your help!

**Comment by jupytera** [comment]
> Thank you for your attention for our work. In the file finetune_diffusion.py, for the sake of convenient testing, we have directly employed a multitude of CLIP models to compose a simplified, readily deployable version of the Context-Aware Adapter, present in the code as MultiCLIP. Should you require the utilization of a Context-Aware Adapter trained by yourself, a few minor adjustments in the code are all that is necessary to substitute MultiCLIP with your own trained Context-Aware Adapter.

Thank you for your answer! After completing the first step, I started running the finetune_diffusion.py. But I find whether I use three pretrained models in MultiCLIP or the model I trained, the following error message will appear:
Traceback (most recent call last):
File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/clip/clip.py", line 129, in load
model = torch.jit.load(opened_file, map_location=device if jit else "cpu").eval()
File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/torch/jit/_serialization.py", line 164, in load
cpp_module = torch._C.import_ir_module_from_buffer(
RuntimeError: PytorchStreamReader failed locating file constants.pkl: file not found
﻿
During handling of the above exception, another exception occurred:
﻿
Traceback (most recent call last):
File "/root/autodl-tmp/ContextDiff-main/ContextDiff_image/finetune_diffusion.py", line 877, in
main()
File "/root/autodl-tmp/ContextDiff-main/ContextDiff_image/finetune_diffusion.py", line 444, in main
clip_model = MultiCLIP()
File "/root/autodl-tmp/ContextDiff-main/ContextDiff_image/finetune_diffusion.py", line 51, in init
model_myself,_ = clip.load("/root/autodl-tmp/ContextDiff-main/output/prior.pt", device=device)
File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/clip/clip.py", line 136, in load
state_dict = torch.load(opened_file, map_location="cpu")
File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/torch/serialization.py", line 713, in load
return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
File "/root/miniconda3/envs/ContextDiff/lib/python3.8/site-packages/torch/serialization.py", line 920, in _legacy_load
magic_number = pickle_module.load(f, **pickle_load_args)
EOFError: Ran out of input
I don't know if this has ever happened in your experiment.
﻿
I still have one more confusion, the finetune_diffusion.py file seems to contain a complete training process. After the training is completed, how should we independently use the obtained model? Thank you again for your help!

**Comment by jupytera** [comment]
> Thank you for your attention for our work. In the file finetune_diffusion.py, for the sake of convenient testing, we have directly employed a multitude of CLIP models to compose a simplified, readily deployable version of the Context-Aware Adapter, present in the code as MultiCLIP. Should you require the utilization of a Context-Aware Adapter trained by yourself, a few minor adjustments in the code are all that is necessary to substitute MultiCLIP with your own trained Context-Aware Adapter.

Thank you for your reply! It seems that the model trained by train_adapter.py is a ClipPrior model, which is different from other pretrained models in use. I don't know how to adjust the code, would you glad to give some instructions?
